name: Ruff

on:
  pull_request:
    paths:
      - 'panorama/**'
      - 'tests/**'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check