name: Ruff

on: [ pull_request ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          use_pyproject: true
          args: format --check
          src: "panorama/ tests/"

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          use_pyproject: true
          args: check
          src: "panorama/ tests/"
